# Generated by Django 6.0.1 on 2026-01-26 09:52

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80, null=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('password_salt', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('visibility', models.CharField(choices=[('private', 'private'), ('public', 'public'), ('unlisted', 'unlisted')], default='private', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='core.pet')),
            ],
            options={
                'db_table': 'chat_sessions',
            },
        ),
        migrations.CreateModel(
            name='PetActionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('pet', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='core.pet')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='pet_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pet_action_log',
            },
        ),
        migrations.CreateModel(
            name='PetAsset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_image_url', models.TextField()),
                ('cutout_image_url', models.TextField(blank=True, null=True)),
                ('model_3d_url', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('image', 'image'), ('3d', '3d'), ('other', 'other')], default='image', max_length=20)),
                ('generator', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ready', 'ready'), ('failed', 'failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('pet', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.pet')),
            ],
            options={
                'db_table': 'pet_assets',
            },
        ),
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=80)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('resolved', 'resolved'), ('rejected', 'rejected')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter_user', models.ForeignKey(blank=True, db_column='reporter_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(blank=True, db_column='pet_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.pet')),
                ('asset', models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.petasset')),
            ],
            options={
                'db_table': 'moderation_reports',
            },
        ),
        migrations.CreateModel(
            name='ContentScan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=60)),
                ('verdict', models.CharField(max_length=30)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='content_scans', to='core.petasset')),
            ],
            options={
                'db_table': 'content_scans',
            },
        ),
        migrations.CreateModel(
            name='PetLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('pet', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.pet')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='pet_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pet_likes',
            },
        ),
        migrations.CreateModel(
            name='PetPersonality',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('roleplay_prompt', models.TextField()),
                ('traits', models.JSONField(default=dict)),
                ('tone', models.CharField(blank=True, max_length=40, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pet', models.OneToOneField(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, related_name='personality', to='core.pet')),
            ],
            options={
                'db_table': 'pet_personalities',
            },
        ),
        migrations.CreateModel(
            name='PetStats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hunger', models.IntegerField(default=50)),
                ('energy', models.IntegerField(default=50)),
                ('happiness', models.IntegerField(default=50)),
                ('cleanliness', models.IntegerField(default=50)),
                ('health', models.IntegerField(default=100)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pet', models.OneToOneField(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.pet')),
            ],
            options={
                'db_table': 'pet_stats',
            },
        ),
        migrations.CreateModel(
            name='UserPetFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('pet', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='core.pet')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='pet_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_pet_follows',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='core.role')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('refresh_token_hash', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_sessions',
                'indexes': [models.Index(fields=['user', 'expires_at'], name='idx_asess_user_expires')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'user'), ('pet', 'pet'), ('system', 'system')], max_length=20)),
                ('content', models.TextField()),
                ('tokens_in', models.IntegerField(blank=True, null=True)),
                ('tokens_out', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'indexes': [models.Index(fields=['session', 'created_at'], name='idx_cmsg_sess_created')],
            },
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner'], name='idx_pets_owner_id'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['visibility'], name='idx_pets_visibility'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['pet'], name='idx_chat_sessions_pet_id'),
        ),
        migrations.AddIndex(
            model_name='petactionlog',
            index=models.Index(fields=['pet', 'created_at'], name='idx_pact_pet_created'),
        ),
        migrations.AddIndex(
            model_name='petasset',
            index=models.Index(fields=['pet'], name='idx_pet_assets_pet_id'),
        ),
        migrations.AddIndex(
            model_name='moderationreport',
            index=models.Index(fields=['status', 'created_at'], name='idx_mrep_status_created'),
        ),
        migrations.AddIndex(
            model_name='contentscan',
            index=models.Index(fields=['asset', 'created_at'], name='idx_cscan_asset_created'),
        ),
        migrations.AddConstraint(
            model_name='petlike',
            constraint=models.UniqueConstraint(fields=('user', 'pet'), name='uniq_user_pet_like'),
        ),
        migrations.AddConstraint(
            model_name='petstats',
            constraint=models.CheckConstraint(condition=models.Q(('hunger__gte', 0), ('hunger__lte', 100)), name='chk_pet_stats_hunger_0_100'),
        ),
        migrations.AddConstraint(
            model_name='petstats',
            constraint=models.CheckConstraint(condition=models.Q(('energy__gte', 0), ('energy__lte', 100)), name='chk_pet_stats_energy_0_100'),
        ),
        migrations.AddConstraint(
            model_name='petstats',
            constraint=models.CheckConstraint(condition=models.Q(('happiness__gte', 0), ('happiness__lte', 100)), name='chk_pet_stats_happiness_0_100'),
        ),
        migrations.AddConstraint(
            model_name='petstats',
            constraint=models.CheckConstraint(condition=models.Q(('cleanliness__gte', 0), ('cleanliness__lte', 100)), name='chk_pet_stats_cleanliness_0_100'),
        ),
        migrations.AddConstraint(
            model_name='petstats',
            constraint=models.CheckConstraint(condition=models.Q(('health__gte', 0), ('health__lte', 100)), name='chk_pet_stats_health_0_100'),
        ),
        migrations.AddConstraint(
            model_name='petstats',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='chk_pet_stats_level_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='petstats',
            constraint=models.CheckConstraint(condition=models.Q(('experience__gte', 0)), name='chk_pet_stats_experience_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='userpetfollow',
            constraint=models.UniqueConstraint(fields=('user', 'pet'), name='uniq_user_pet_follow'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uniq_user_role'),
        ),
    ]
