# Generated by Django 6.0.1 on 2026-02-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personality'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personality',
            new_name='temp_personality',
        ),
    ]
