# Generated by Django 6.0.1 on 2026-02-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_personality_temp_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_personality',
            name='prompt',
            field=models.TextField(max_length=500),
        ),
    ]
