# Generated by Django 6.0.1 on 2026-02-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_temp_personality_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='stats_before_last_message',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
