# Generated by Django 6.0.2 on 2026-03-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatsession_stats_before_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpersonality',
            name='stat_reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
