# Generated by Django 6.0.2 on 2026-03-18 01:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_petpersonality_stat_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_summarized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChatMessageVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.chatmessage')),
            ],
            options={
                'db_table': 'chat_message_versions',
                'ordering': ['version_number'],
                'indexes': [models.Index(fields=['message', 'version_number'], name='idx_cmv_message_version')],
            },
        ),
        migrations.CreateModel(
            name='ChatSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_text', models.TextField()),
                ('covers_up_to_message_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='core.chatsession')),
            ],
            options={
                'db_table': 'chat_summaries',
                'indexes': [models.Index(fields=['session', 'created_at'], name='idx_csum_session_created')],
            },
        ),
    ]
