# Generated by Django 6.0.2 on 2026-03-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chatmessage_is_summarized_chatmessageversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessageversion',
            name='stat_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
