# Generated by Django 6.0.2 on 2026-03-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatmessageversion_stat_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpersonality',
            name='opening_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
